wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1706296504.379287
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.11.5
      5: 0.15.11
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
